"""empty message

Revision ID: 74059a29fbca
Revises: 21b03b6ecfd9
Create Date: 2022-09-24 09:16:10.372478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74059a29fbca'
down_revision = '21b03b6ecfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reptiles', sa.Column('common_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reptiles', 'common_name')
    # ### end Alembic commands ###
